{% set name = "executing" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c2c07d1ec4b2d8f9676b25170f1d8445c0ee2eb78901afb075a4b8d83608c6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
    - setuptools_scm
  run:
    - python >=2.7

test:
  imports:
    - executing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/executing
  summary: Get the currently executing AST node of a frame, and other information
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/alexmojaki/executing

extra:
  recipe-maintainers:
    - alexmojaki
    - anthchirp
